version: "3"

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
    restart: always

  project:
    build:
      context: .
    volumes:
      - .:/project
    depends_on:
      - selenium